server:
  port: 8888

security: 
    basic: 
        enable: true
    user: 
        name: admin
        password: 123yys 

eureka:
  server:
    enable-self-preservation: true
    renewalPercentThreshold: 0.49
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/